[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:samba]
command=/usr/sbin/samba -i --no-process-group
autostart=true
autorestart=true
stdout_logfile=/var/log/samba/samba.log
stderr_logfile=/var/log/samba/samba_error.log
priority=1

[program:winbind]
command=/usr/sbin/winbindd -F
autostart=true
autorestart=true
stdout_logfile=/var/log/samba/winbind.log
stderr_logfile=/var/log/samba/winbind_error.log
priority=2
