-- CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWD}';

-- Create backend database
CREATE DATABASE ${BACKEND_DB_NAME};
GRANT ALL PRIVILEGES ON DATABASE ${BACKEND_DB_NAME} TO ${DB_USER};

-- Create auth database
CREATE DATABASE ${AUTH_DB_NAME};
GRANT ALL PRIVILEGES ON DATABASE ${AUTH_DB_NAME} TO ${DB_USER};

-- Grant privileges on tables (will be applied when tables are created)
\c ${BACKEND_DB_NAME}
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DB_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DB_USER};
GRANT ALL PRIVILEGES ON SCHEMA public TO ${DB_USER};

\c ${AUTH_DB_NAME}
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DB_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DB_USER};
GRANT ALL PRIVILEGES ON SCHEMA public TO ${DB_USER};